name: Editorial Checks

on:
  push:
    paths:
    - 'docs/**'

jobs:
  build-and-test:
    name: Check Wording
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock')}}

      - name: Install
        working-directory: .
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Alex Lint
        run: yarn docs:alex
