name: LinkCheck

on:
  pull_request:
    branches:
      - main
    paths:
    - 'docs/**'
  push:
    paths:
    - 'docs/**'

jobs:
  link-check:
    strategy:
      matrix:
        file-extension: [.md]
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: gaurav-nelson/github-action-markdown-link-check@1.0.12
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.mlc_config.json'
        #check-modified-files-only: 'yes'
        folder-path: 'docs'
